import "./index.scss";
import Input from "../Input/Input";
import CardInput from "../CardInput/CardInput";
import { useEffect, useState } from "react";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export default function WeatherContent() {
  const [city, setCity] = useState("");
  const [onSearchCity, setOnSearchCity] = useState(false);
  const [weatherData, setWeatherData] = useState(null);

  useEffect(() => {
    async function getCity() {
      let dataResponse = await fetch(
        `https://api.weatherapi.com/v1/forecast.json?key=e63768fb567b4a2b822125329231105&q=${city}&lang=pt`
      );
      let data = await dataResponse.json();
      if (data.error) {
        toast.error("Cidade não encontrada!");
        return;
      }
      if (data) {
        toast.success("Cidade encontrada!");
      }
      setWeatherData(data);
      setCity("");
    }

    if (onSearchCity == true) {
      getCity();
      setOnSearchCity(false);
    }
  }, [onSearchCity]);

  const searchCity = (canSearch) => {
    setOnSearchCity(canSearch);
  };

  return (
    <>
      <ToastContainer autoClose={1000} theme="dark" />
      {weatherData && (
        <CardInput
          onSearchCity={onSearchCity}
          setOnSearchCity={setOnSearchCity}
          city={city}
          weatherData={weatherData}
        />
      )}
      <Input setCity={setCity} searchCity={searchCity} city={city} />
    </>
  );
}

/*
{
    "location": {
        "name": "London",
        "region": "City of London, Greater London",
        "country": "United Kingdom",
        "lat": 51.52,
        "lon": -0.11,
        "tz_id": "Europe/London",
        "localtime_epoch": 1684770551,
        "localtime": "2023-05-22 16:49"
    },
    "current": {
        "last_updated_epoch": 1684770300,
        "last_updated": "2023-05-22 16:45",
        "temp_c": 19,
        "temp_f": 66.2,
        "is_day": 1,
        "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
        },
        "wind_mph": 16.1,
        "wind_kph": 25.9,
        "wind_degree": 20,
        "wind_dir": "NNE",
        "pressure_mb": 1021,
        "pressure_in": 30.15,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 52,
        "cloud": 0,
        "feelslike_c": 19,
        "feelslike_f": 66.2,
        "vis_km": 10,
        "vis_miles": 6,
        "uv": 5,
        "gust_mph": 16.1,
        "gust_kph": 25.9
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2023-05-22",
                "date_epoch": 1684713600,
                "day": {
                    "maxtemp_c": 18.8,
                    "maxtemp_f": 65.8,
                    "mintemp_c": 8.8,
                    "mintemp_f": 47.8,
                    "avgtemp_c": 13.8,
                    "avgtemp_f": 56.9,
                    "maxwind_mph": 14.1,
                    "maxwind_kph": 22.7,
                    "totalprecip_mm": 0,
                    "totalprecip_in": 0,
                    "totalsnow_cm": 0,
                    "avgvis_km": 10,
                    "avgvis_miles": 6,
                    "avghumidity": 68,
                    "daily_will_it_rain": 0,
                    "daily_chance_of_rain": 0,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Partly cloudy",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                        "code": 1003
                    },
                    "uv": 4
                },
                "astro": {
                    "sunrise": "04:59 AM",
                    "sunset": "08:56 PM",
                    "moonrise": "06:21 AM",
                    "moonset": "No moonset",
                    "moon_phase": "Waxing Crescent",
                    "moon_illumination": "6",
                    "is_moon_up": 0,
                    "is_sun_up": 0
                },
                "hour": [
                    {
                        "time_epoch": 1684710000,
                        "time": "2023-05-22 00:00",
                        "temp_c": 9.8,
                        "temp_f": 49.6,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.9,
                        "wind_kph": 11.2,
                        "wind_degree": 358,
                        "wind_dir": "N",
                        "pressure_mb": 1020,
                        "pressure_in": 30.13,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 84,
                        "cloud": 6,
                        "feelslike_c": 8.2,
                        "feelslike_f": 46.8,
                        "windchill_c": 8.2,
                        "windchill_f": 46.8,
                        "heatindex_c": 9.8,
                        "heatindex_f": 49.6,
                        "dewpoint_c": 7.2,
                        "dewpoint_f": 45,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 10.7,
                        "gust_kph": 17.3,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1684713600,
                        "time": "2023-05-22 01:00",
                        "temp_c": 9.4,
                        "temp_f": 48.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.9,
                        "wind_kph": 11.2,
                        "wind_degree": 353,
                        "wind_dir": "N",
                        "pressure_mb": 1020,
                        "pressure_in": 30.12,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 84,
                        "cloud": 5,
                        "feelslike_c": 7.7,
                        "feelslike_f": 45.9,
                        "windchill_c": 7.7,
                        "windchill_f": 45.9,
                        "heatindex_c": 9.4,
                        "heatindex_f": 48.9,
                        "dewpoint_c": 6.8,
                        "dewpoint_f": 44.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 11.2,
                        "gust_kph": 18,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1684717200,
                        "time": "2023-05-22 02:00",
                        "temp_c": 9.1,
                        "temp_f": 48.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 7.4,
                        "wind_kph": 11.9,
                        "wind_degree": 354,
                        "wind_dir": "N",
                        "pressure_mb": 1020,
                        "pressure_in": 30.11,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 83,
                        "cloud": 19,
                        "feelslike_c": 7.2,
                        "feelslike_f": 45,
                        "windchill_c": 7.2,
                        "windchill_f": 45,
                        "heatindex_c": 9.1,
                        "heatindex_f": 48.4,
                        "dewpoint_c": 6.4,
                        "dewpoint_f": 43.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 12.1,
                        "gust_kph": 19.4,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1684720800,
                        "time": "2023-05-22 03:00",
                        "temp_c": 9,
                        "temp_f": 48.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 6.7,
                        "wind_kph": 10.8,
                        "wind_degree": 353,
                        "wind_dir": "N",
                        "pressure_mb": 1020,
                        "pressure_in": 30.11,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 85,
                        "cloud": 50,
                        "feelslike_c": 7.3,
                        "feelslike_f": 45.1,
                        "windchill_c": 7.3,
                        "windchill_f": 45.1,
                        "heatindex_c": 9,
                        "heatindex_f": 48.2,
                        "dewpoint_c": 6.6,
                        "dewpoint_f": 43.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 11,
                        "gust_kph": 17.6,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1684724400,
                        "time": "2023-05-22 04:00",
                        "temp_c": 8.8,
                        "temp_f": 47.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                            "code": 1006
                        },
                        "wind_mph": 6.5,
                        "wind_kph": 10.4,
                        "wind_degree": 352,
                        "wind_dir": "N",
                        "pressure_mb": 1020,
                        "pressure_in": 30.11,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 85,
                        "cloud": 69,
                        "feelslike_c": 7.1,
                        "feelslike_f": 44.8,
                        "windchill_c": 7.1,
                        "windchill_f": 44.8,
                        "heatindex_c": 8.8,
                        "heatindex_f": 47.8,
                        "dewpoint_c": 6.4,
                        "dewpoint_f": 43.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 10.7,
                        "gust_kph": 17.3,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1684728000,
                        "time": "2023-05-22 05:00",
                        "temp_c": 9.3,
                        "temp_f": 48.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                            "code": 1006
                        },
                        "wind_mph": 6.7,
                        "wind_kph": 10.8,
                        "wind_degree": 348,
                        "wind_dir": "NNW",
                        "pressure_mb": 1020,
                        "pressure_in": 30.11,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 82,
                        "cloud": 64,
                        "feelslike_c": 7.7,
                        "feelslike_f": 45.9,
                        "windchill_c": 7.7,
                        "windchill_f": 45.9,
                        "heatindex_c": 9.3,
                        "heatindex_f": 48.7,
                        "dewpoint_c": 6.3,
                        "dewpoint_f": 43.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 10.5,
                        "gust_kph": 16.9,
                        "uv": 2
                    },
                    {
                        "time_epoch": 1684731600,
                        "time": "2023-05-22 06:00",
                        "temp_c": 10.9,
                        "temp_f": 51.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 8.5,
                        "wind_kph": 13.7,
                        "wind_degree": 349,
                        "wind_dir": "N",
                        "pressure_mb": 1020,
                        "pressure_in": 30.11,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 75,
                        "cloud": 48,
                        "feelslike_c": 9.2,
                        "feelslike_f": 48.6,
                        "windchill_c": 9.2,
                        "windchill_f": 48.6,
                        "heatindex_c": 10.9,
                        "heatindex_f": 51.6,
                        "dewpoint_c": 6.6,
                        "dewpoint_f": 43.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 11.4,
                        "gust_kph": 18.4,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1684735200,
                        "time": "2023-05-22 07:00",
                        "temp_c": 12.7,
                        "temp_f": 54.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 10.1,
                        "wind_kph": 16.2,
                        "wind_degree": 350,
                        "wind_dir": "N",
                        "pressure_mb": 1020,
                        "pressure_in": 30.11,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 68,
                        "cloud": 34,
                        "feelslike_c": 11.1,
                        "feelslike_f": 52,
                        "windchill_c": 11.1,
                        "windchill_f": 52,
                        "heatindex_c": 12.7,
                        "heatindex_f": 54.9,
                        "dewpoint_c": 6.9,
                        "dewpoint_f": 44.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 12.3,
                        "gust_kph": 19.8,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1684738800,
                        "time": "2023-05-22 08:00",
                        "temp_c": 14.5,
                        "temp_f": 58.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 11,
                        "wind_kph": 17.6,
                        "wind_degree": 351,
                        "wind_dir": "N",
                        "pressure_mb": 1020,
                        "pressure_in": 30.12,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 63,
                        "cloud": 22,
                        "feelslike_c": 13.2,
                        "feelslike_f": 55.8,
                        "windchill_c": 13.2,
                        "windchill_f": 55.8,
                        "heatindex_c": 14.5,
                        "heatindex_f": 58.1,
                        "dewpoint_c": 7.5,
                        "dewpoint_f": 45.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 12.5,
                        "gust_kph": 20.2,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1684742400,
                        "time": "2023-05-22 09:00",
                        "temp_c": 16,
                        "temp_f": 60.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                            "code": 1006
                        },
                        "wind_mph": 12.1,
                        "wind_kph": 19.4,
                        "wind_degree": 354,
                        "wind_dir": "N",
                        "pressure_mb": 1020,
                        "pressure_in": 30.13,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 60,
                        "cloud": 63,
                        "feelslike_c": 16,
                        "feelslike_f": 60.8,
                        "windchill_c": 16,
                        "windchill_f": 60.8,
                        "heatindex_c": 16,
                        "heatindex_f": 60.8,
                        "dewpoint_c": 8.2,
                        "dewpoint_f": 46.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 13.9,
                        "gust_kph": 22.3,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1684746000,
                        "time": "2023-05-22 10:00",
                        "temp_c": 17,
                        "temp_f": 62.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Overcast",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                            "code": 1009
                        },
                        "wind_mph": 13.9,
                        "wind_kph": 22.3,
                        "wind_degree": 355,
                        "wind_dir": "N",
                        "pressure_mb": 1020,
                        "pressure_in": 30.13,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 57,
                        "cloud": 100,
                        "feelslike_c": 17,
                        "feelslike_f": 62.6,
                        "windchill_c": 17,
                        "windchill_f": 62.6,
                        "heatindex_c": 17,
                        "heatindex_f": 62.6,
                        "dewpoint_c": 8.4,
                        "dewpoint_f": 47.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 15.9,
                        "gust_kph": 25.6,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1684749600,
                        "time": "2023-05-22 11:00",
                        "temp_c": 15.8,
                        "temp_f": 60.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Overcast",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                            "code": 1009
                        },
                        "wind_mph": 13.4,
                        "wind_kph": 21.6,
                        "wind_degree": 355,
                        "wind_dir": "N",
                        "pressure_mb": 1021,
                        "pressure_in": 30.14,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 61,
                        "cloud": 88,
                        "feelslike_c": 15.8,
                        "feelslike_f": 60.4,
                        "windchill_c": 15.8,
                        "windchill_f": 60.4,
                        "heatindex_c": 15.8,
                        "heatindex_f": 60.4,
                        "dewpoint_c": 8.2,
                        "dewpoint_f": 46.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 15.4,
                        "gust_kph": 24.8,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1684753200,
                        "time": "2023-05-22 12:00",
                        "temp_c": 16.4,
                        "temp_f": 61.5,
                        "is_day": 1,
                        "condition": {
                            "text": "Cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                            "code": 1006
                        },
                        "wind_mph": 13,
                        "wind_kph": 20.9,
                        "wind_degree": 356,
                        "wind_dir": "N",
                        "pressure_mb": 1021,
                        "pressure_in": 30.14,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 61,
                        "cloud": 67,
                        "feelslike_c": 16.4,
                        "feelslike_f": 61.5,
                        "windchill_c": 16.4,
                        "windchill_f": 61.5,
                        "heatindex_c": 16.4,
                        "heatindex_f": 61.5,
                        "dewpoint_c": 9,
                        "dewpoint_f": 48.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 15,
                        "gust_kph": 24.1,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1684756800,
                        "time": "2023-05-22 13:00",
                        "temp_c": 18.5,
                        "temp_f": 65.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Overcast",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                            "code": 1009
                        },
                        "wind_mph": 13.4,
                        "wind_kph": 21.6,
                        "wind_degree": 356,
                        "wind_dir": "N",
                        "pressure_mb": 1020,
                        "pressure_in": 30.12,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 57,
                        "cloud": 100,
                        "feelslike_c": 18.5,
                        "feelslike_f": 65.3,
                        "windchill_c": 18.5,
                        "windchill_f": 65.3,
                        "heatindex_c": 18.5,
                        "heatindex_f": 65.3,
                        "dewpoint_c": 9.9,
                        "dewpoint_f": 49.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 15.4,
                        "gust_kph": 24.8,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1684760400,
                        "time": "2023-05-22 14:00",
                        "temp_c": 18.8,
                        "temp_f": 65.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Overcast",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                            "code": 1009
                        },
                        "wind_mph": 14.1,
                        "wind_kph": 22.7,
                        "wind_degree": 3,
                        "wind_dir": "N",
                        "pressure_mb": 1020,
                        "pressure_in": 30.12,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 58,
                        "cloud": 93,
                        "feelslike_c": 18.8,
                        "feelslike_f": 65.8,
                        "windchill_c": 18.8,
                        "windchill_f": 65.8,
                        "heatindex_c": 18.8,
                        "heatindex_f": 65.8,
                        "dewpoint_c": 10.3,
                        "dewpoint_f": 50.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 16.1,
                        "gust_kph": 25.9,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1684764000,
                        "time": "2023-05-22 15:00",
                        "temp_c": 18.5,
                        "temp_f": 65.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                            "code": 1006
                        },
                        "wind_mph": 13.6,
                        "wind_kph": 22,
                        "wind_degree": 7,
                        "wind_dir": "N",
                        "pressure_mb": 1020,
                        "pressure_in": 30.12,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 59,
                        "cloud": 79,
                        "feelslike_c": 18.5,
                        "feelslike_f": 65.3,
                        "windchill_c": 18.5,
                        "windchill_f": 65.3,
                        "heatindex_c": 18.5,
                        "heatindex_f": 65.3,
                        "dewpoint_c": 10.3,
                        "dewpoint_f": 50.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 15.7,
                        "gust_kph": 25.2,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1684767600,
                        "time": "2023-05-22 16:00",
                        "temp_c": 18.5,
                        "temp_f": 65.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 14.1,
                        "wind_kph": 22.7,
                        "wind_degree": 8,
                        "wind_dir": "N",
                        "pressure_mb": 1020,
                        "pressure_in": 30.13,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 58,
                        "cloud": 61,
                        "feelslike_c": 18.5,
                        "feelslike_f": 65.3,
                        "windchill_c": 18.5,
                        "windchill_f": 65.3,
                        "heatindex_c": 18.5,
                        "heatindex_f": 65.3,
                        "dewpoint_c": 10.1,
                        "dewpoint_f": 50.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 16.1,
                        "gust_kph": 25.9,
                        "uv": 5
                    },
                    {
                        "time_epoch": 1684771200,
                        "time": "2023-05-22 17:00",
                        "temp_c": 17.9,
                        "temp_f": 64.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 13.6,
                        "wind_kph": 22,
                        "wind_degree": 8,
                        "wind_dir": "N",
                        "pressure_mb": 1021,
                        "pressure_in": 30.14,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 60,
                        "cloud": 22,
                        "feelslike_c": 17.9,
                        "feelslike_f": 64.2,
                        "windchill_c": 17.9,
                        "windchill_f": 64.2,
                        "heatindex_c": 17.9,
                        "heatindex_f": 64.2,
                        "dewpoint_c": 10,
                        "dewpoint_f": 50,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 15.7,
                        "gust_kph": 25.2,
                        "uv": 5
                    },
                    {
                        "time_epoch": 1684774800,
                        "time": "2023-05-22 18:00",
                        "temp_c": 16.9,
                        "temp_f": 62.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 11.9,
                        "wind_kph": 19.1,
                        "wind_degree": 10,
                        "wind_dir": "N",
                        "pressure_mb": 1021,
                        "pressure_in": 30.16,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 62,
                        "cloud": 38,
                        "feelslike_c": 16.9,
                        "feelslike_f": 62.4,
                        "windchill_c": 16.9,
                        "windchill_f": 62.4,
                        "heatindex_c": 16.9,
                        "heatindex_f": 62.4,
                        "dewpoint_c": 9.7,
                        "dewpoint_f": 49.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 13.6,
                        "gust_kph": 22,
                        "uv": 5
                    },
                    {
                        "time_epoch": 1684778400,
                        "time": "2023-05-22 19:00",
                        "temp_c": 15.6,
                        "temp_f": 60.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 11,
                        "wind_kph": 17.6,
                        "wind_degree": 10,
                        "wind_dir": "N",
                        "pressure_mb": 1022,
                        "pressure_in": 30.18,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 64,
                        "cloud": 26,
                        "feelslike_c": 15.6,
                        "feelslike_f": 60.1,
                        "windchill_c": 15.6,
                        "windchill_f": 60.1,
                        "heatindex_c": 15.6,
                        "heatindex_f": 60.1,
                        "dewpoint_c": 8.7,
                        "dewpoint_f": 47.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 13,
                        "gust_kph": 20.9,
                        "uv": 5
                    },
                    {
                        "time_epoch": 1684782000,
                        "time": "2023-05-22 20:00",
                        "temp_c": 13.3,
                        "temp_f": 55.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 12,
                        "wind_dir": "NNE",
                        "pressure_mb": 1023,
                        "pressure_in": 30.2,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 64,
                        "cloud": 19,
                        "feelslike_c": 11.9,
                        "feelslike_f": 53.4,
                        "windchill_c": 11.9,
                        "windchill_f": 53.4,
                        "heatindex_c": 13.3,
                        "heatindex_f": 55.9,
                        "dewpoint_c": 6.6,
                        "dewpoint_f": 43.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 14.3,
                        "gust_kph": 23,
                        "uv": 4
                    },
                    {
                        "time_epoch": 1684785600,
                        "time": "2023-05-22 21:00",
                        "temp_c": 12.3,
                        "temp_f": 54.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.8,
                        "wind_kph": 15.8,
                        "wind_degree": 9,
                        "wind_dir": "N",
                        "pressure_mb": 1024,
                        "pressure_in": 30.22,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 64,
                        "cloud": 12,
                        "feelslike_c": 10.7,
                        "feelslike_f": 51.3,
                        "windchill_c": 10.7,
                        "windchill_f": 51.3,
                        "heatindex_c": 12.3,
                        "heatindex_f": 54.1,
                        "dewpoint_c": 5.6,
                        "dewpoint_f": 42.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 14.5,
                        "gust_kph": 23.4,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1684789200,
                        "time": "2023-05-22 22:00",
                        "temp_c": 11.5,
                        "temp_f": 52.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.8,
                        "wind_kph": 15.8,
                        "wind_degree": 9,
                        "wind_dir": "N",
                        "pressure_mb": 1024,
                        "pressure_in": 30.24,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 65,
                        "cloud": 0,
                        "feelslike_c": 9.7,
                        "feelslike_f": 49.5,
                        "windchill_c": 9.7,
                        "windchill_f": 49.5,
                        "heatindex_c": 11.5,
                        "heatindex_f": 52.7,
                        "dewpoint_c": 5.2,
                        "dewpoint_f": 41.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 14.3,
                        "gust_kph": 23,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1684792800,
                        "time": "2023-05-22 23:00",
                        "temp_c": 10.9,
                        "temp_f": 51.6,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 8.3,
                        "wind_kph": 13.3,
                        "wind_degree": 9,
                        "wind_dir": "N",
                        "pressure_mb": 1024,
                        "pressure_in": 30.25,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 69,
                        "cloud": 0,
                        "feelslike_c": 9.2,
                        "feelslike_f": 48.6,
                        "windchill_c": 9.2,
                        "windchill_f": 48.6,
                        "heatindex_c": 10.9,
                        "heatindex_f": 51.6,
                        "dewpoint_c": 5.4,
                        "dewpoint_f": 41.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 12.1,
                        "gust_kph": 19.4,
                        "uv": 1
                    }
                ]
            }
        ]
    }
}
*/
